# Generated by Django 6.0.2 on 2026-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('resim', models.ImageField(blank=True, upload_to='parcalar/')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aciklama', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cihaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('resim', models.ImageField(blank=True, upload_to='cihazlar/')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kisa_aciklama', models.CharField(help_text='Kartın üzerinde görünecek kısa yazı', max_length=300)),
                ('detayli_aciklama', models.TextField(help_text='Pop-up içinde çıkacak detaylı bilgi')),
                ('parcalar', models.ManyToManyField(blank=True, related_name='cihazlar', to='urunler.parca')),
            ],
        ),
    ]
